### ISSUE TITLE
Output in Spinlog

### ISSUE THREAD

**Issue by ssc5** [wschreyer/PENTrack#31]
Is there any reason that the magnetic field components in the spinlog are divided by Babs before being printed (line 62 in bruteforce.cpp)?

**Comment by wschreyer** [comment]
No...
If you want to change it to print out the field components you should remove the Babs output. The files get large enough as it is.

**Comment by ssc5** [comment]
Do you mean I should remove the Babs column from the spinlog or just the division of the Bx, By, Bz field components by Babs?

**Comment by wschreyer** [comment]
Both. If you have the absolute values of Bx, By, and Bz you can calculate Babs, so no need for this extra column.

**Comment by ssc5** [comment]
Ok in the last pull request, I already removed the division by Babs. I will remove the Babs column in the next pull request.
