### ISSUE TITLE
[Question] What is the effect of spinloginterval in TBFIntegrator?

### ISSUE THREAD

**Issue by ssc5** [wschreyer/PENTrack#35]
What does spinloginterval in TBFIntegrator class do? 

When I run a simulation using TEDMStaticB0GradZField  with edmB0z0 = 1e-6 and edmdB0z0dz = 1e-9 and spinloginterval set to 5E-7, the output in the spinlog is printed ever 5E-7 seconds but when the spinloginterval is set to 5E-2 the output is at the following times: 0, 0.0001947503937, 0.0001947503937, 0.001071127165, 0.001071127165, 0.003018486483, 0.003018486483 ....

As you can see the output is no longer every 5E-2 seconds as expected from the function of 5E-2 but some unit of time that is much smaller and each row of output is being repeated twice. 

Why does this happens? How does boost use the "times" vector constructed in TBFIntegrator::Integrate to determine when the output is done?

The reason I ask is because in the latest pull request I have added an option that updates that directly controls when the output to the spinlog is done.

**Comment by wschreyer** [comment]
The `integrate_times` routine of the odeint library integrates the ODE and calls the observer function at every time contained in the `times` vector. The `times` vector contains the beginning `x1`, intermediate points `x1 + N*spinloginterval`, and the end of each particle trajectory step.
I never assumed, that the particle trajectory step `x2 - x1` could be shorter than `spinloginterval`. Then of course you get only entries at `x1` and `x2`, and all of them doubled.
Your new timing variable actually makes more sense, feel free to replace the old `spinloginterval`.

**Comment by ssc5** [comment]
Oh I see so when the spinlog interval is bigger than the particle trajectory step, the output only happens at `x1` and `x2` and then when the next step occurs the new `x1` is actually the old `x2` so that's why there's two outputs? Ok I'll delete the `spinloginterval` option since the `spinlogtimeinterval` has already been added.

**Comment by ssc5** [comment]
I don't think this is actually completely correct or maybe we were thinking of final goals. What I was hoping to implement is a variable that produces output at any arbitrary interval in the spinlog. So you would be able to output a measurement in the spinlog every 0.5 seconds and no time in between, the entries in the spin log would then be at 0, 0.5, 1, 1.5, 2, 2.5 .... 

However in the scheme that is currently implemented, if spinloginterval is set to 0.5 then the output would occur at every 0 and then every value of `x2`, which I think we don't want. Rather we want an output at 0, ~0.5, ~1, ~1.5 .... Moreover, the `if` statement you added in commit 7bb1a21  is never triggered and the `while` loop is only triggered in the first call to `TBFIntegrator::Integrate`. I will add a new commit to the most recent pull request that will try to make the output more like the implementation that I think we both wanted.

**Comment by wschreyer** [comment]
You are right, adding every value of x2 is unnecessary.
I was thinking of the more general case where the integration could be started several times for non-adjacent time intervals. So if it runs from, say, 10s to 11s, the if statement actually is called and starts the logging at 10s. If it is then started again at 20s, the if statement sets the new logging start at 20s and so on.
