### ISSUE TITLE
[Question] Should the E1 and E2 components be displayed in the spinlog?

### ISSUE THREAD

**Issue by ssc5** [wschreyer/PENTrack#37]
Since we have added the vxE effect to the `TBFIntegrator` would it be a good idea to include the value of the E1x, E1y, ..., E2y, E2z into the spinlog? 

I am thinking of adding a new array `double Efield[6]` that belongs to `TBFIntegrator` and stores the values of the E1 and E2 components that are used to call `TBFIntegrator::Integrate`. This array would be initialized in `TBFIntegrator::Integrate` and its components would be printed to `spinlog` in `void TBFIntegrator::operator()(const state_type &y, value_type x)`.

What do you think?

**Comment by wschreyer** [comment]
I'm not sure if it makes sense, since the electric field is already included in the magnetic field output. I guess you would also have to print out velocity?

**Comment by ssc5** [comment]
Yes, you should probably print velocities too. The reason to do this would be so you could know the Bfield contribution from vxE. 

Maybe instead of printing E1 and E2, we could print out the components of v1xE1 and v2xE2?

**Comment by wschreyer** [comment]
Sure, go ahead.

**Comment by wschreyer** [comment]
Fixed in 352a3b60a63eb29b1c529e97b6a09fb52c27b0f8.
