### ISSUE TITLE
boost_1_64_0 not compatible

### ISSUE THREAD

**Issue by dougUCN** [wschreyer/PENTrack#49]
Attempting to make with boost version 1.64.0 gives the message

error: ‘make_array’ is not a member of ‘boost::serialization’

Seems to be a bug with boost, according to google

**Comment by wschreyer** [comment]
Unfortunately, I don't have a system with boost 1.64.0 at hand.
Can you be more specific? In which file the call to make_array causing this error? It's not used in PENTrack's code, so I suspect it's some incompatibility between libraries. What version of CGAL are you using? How was it installed? What compiler version are you using?

**Comment by dougUCN** [comment]
CGAL 4.11.0 (installed via the install_cgal.sh script)
cmake 3.8.0

The error seems to be from file 
boost/gnu/1.64.0/include/boost/numeric/ublas/vector.hpp

Yeah, seems to just be something wrong with this particular build of boost

**Comment by wschreyer** [comment]
Sounds like you switched boost versions at some point? Did you re-compile CGAL after switching? What version did you use before?

**Comment by dougUCN** [comment]
Ah Pentrack works great on my personal comp, was just trying to get it set
up fresh on a computer cluster.

**Comment by wschreyer** [comment]
I just did some experiments with boost 1.65.1. Did you possibly get warnings like this when running cmake?
https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version
Seems like the newer boost version also need one of the later versions of cmake.

**Comment by dougUCN** [comment]
I didn't get those warnings. I ended up using 1.66 and it turned out fine

**Comment by wschreyer** [comment]
Turns out, this is indeed a bug in Boost 1.64.0, see https://svn.boost.org/trac10/ticket/12516
I noted this in the README.

Thanks!
