### ISSUE TITLE
Time dependent fields not working

### ISSUE THREAD

**Issue by dougUCN** [wschreyer/PENTrack#53]
Time dependent fields are not working with spin tracking. Tested briefly on test/Ramsey_up.in with initial neutron polarization set to 1, and I could not see any spin flipping on the spin tracking files.

Doesn't seem to be solely an issue with EDMStaticB0GradZField. I recreated the same test using CustomBField and any time dependent fields were ignored

My initial guess is that the changes to TFieldManager in 3c9427b68c1134a6e7ef47f485b50be92ede4c8e might be the cause, but there have been large changes to field parsing so I'm not sure

**Comment by wschreyer** [comment]
Thanks, there was an issue with the exprtk formula parser. When the new class containing the parser was copied, the variable references stored in the parser were invalidated, resulting in some weird behavior. Previously, the parser was stored in the non-copyable TField class, so it never became an issue before.

Could you give it another try with the latest commit?

**Comment by dougUCN** [comment]
Latest commit works great. runTests also clears without any problems. Thanks so much!
