### ISSUE TITLE
unknown type name ‘hid_t’.  HDF5 library.

### ISSUE THREAD

**Issue by sgoryunov** [wschreyer/PENTrack#55]
Hello!
I tried to compile the PENTrack and faced to a problem with HDF5 library. For now I found workaround solution and switched it off in cmake. But how can I solve it? 
OS: Scientific Linux 7.9 (Nitrogen)

**Comment by wschreyer** [comment]
Hi. I found some bug reports indicating that this may happen due to a header not being included. Can you pull the latest changes and try again?
Thanks!

**Comment by sgoryunov** [comment]
Now all is compiled. Thank you very much!
