### ISSUE TITLE
Scaling not working for EDMStaticEField 

### ISSUE THREAD

**Issue by DillonBusk** [wschreyer/PENTrack#56]
Changing the fourth argument of EDMStaticEField in my config file has no effect on the electric field experienced. 
For example, I set the scale to 0 below, but the particles are still experiencing the full 1e6V/m Ez field when looking at the track log.

#EDMStaticEField    Ex  Ey  Ez  scale 
1 EDMStaticEField 0   0   1e6  0 

This scale option does work as intended when using the COMSOL or CustomBField options, so I figure it is an issue specific to the EDMStaticEField option. 

I looked into the source code briefly and found the following:
Starting on line 85 of /src/fields.cpp I noticed that Bscale is being used instead of the Escale defined in line 27. 

        else if ((type == "EDMStaticEField") and (ss >> p1 >> p2 >> p3 >> Bscale)){
			std::unique_ptr<TField> f(new TEDMStaticEField (p1, p2, p3));
			Bscale = ResolveFormula(Bscale, conf["FORMULAS"]);
            fields.emplace_back(TFieldContainer(std::move(f), Bscale));
		}

What I am observing may be an issue in the code, or just a misunderstanding on my part. However, any feedback would be greatly appreciated.

**Comment by wschreyer** [comment]
Thank you for pointing this out. You are correct that the scaling variable is applied to the magnetic field, which of course has no effect when using the EDMStaticEField. I'm committing a fix that correctly applies it to the electric field.
